const mongoose = require("mongoose");
const paymentSchema = new mongoose.Schema({

    // Result information returned by the Payment gateway
    resultInfo: {
        // Status of the transaction (Sucess/ Failure)
        resultStatus: {
            type: String,
            required: true
        },
        // Response code from the payment gateway
        resultCode: {
            type: String,
            required: true
        },
        // Message describing the transaction result
        resultMsg: {
            type: String,
            required: true 
        },
    },

    // Unique transaction ID generated by payment gateway
    txnId: {
        type: String,
        required: true
    },

    // Transaction ID Provided by the bank
    bankTxnId: {
        type: String,
        required: true 
    },

    // order ID associated with the Transaction
    orderId: {
        type: String,
        required: true
    },

    // Amount paid in the transaction
    txnAmount: {
        type: String,
        required: true 
    },

    // Type of Transaction (PAYMENT/ REFUND)
    txnType: {
        type: String,
        required: true
    },

    // Name of the Payment gateway (Paytm, Razorpay)
    gatewayName: {
        type: String,
        required: true
    },

    // Name of the bank used for transaction
    bankName: {
        type: String,
        required: true

    },

    // Merchant ID Provided by payment gateway
    mid: {
        type: String,
        required: true
    },

    // Mode of Payment (UPI, CARD, NETBANKING)
    paymentMode: {
        type: String,
        required: true
    },

    // refunded Amount
    refundAmnt: {
        type: String,
        required: true
    },

    // Date and time of the Transaction
    txnDate: {
        type: String,
        required: true
    },

    // Timestamp when the record is created in MongoDB
    createdAt: {
        type: Date,
        default: Date.now
    }

});

// Export payment Model
module.exports = mongoose.model("Payment", paymentSchema);